export const TITLES = {
	CREATE_NOTE: 'Create note',
	CHOOSE_NOTE: 'Choose note',
	PREVIEW: 'Preview',
	EDIT: 'Edit',
	TITLE_PLACEHOLDER: 'Title...',
	NOTE_PLACEHOLDER: 'Note...',
	NOTHING_FOUND: 'Nothing found...',
	GUEST: 'Guest',
	LOGIN: 'Login',
	SIGN_IN_NOTES: 'Sign in Notes',
	CANCEL: 'Cancel',
	REMOVE: 'Remove',
	REMOVE_NOTE: 'Remove this note?',
	SAVE: 'Save',
	SEARCH_PLACEHOLDER: 'Search...',
	USERNAME: 'username',
	USER: 'user',
	ENTER_USERNAME: 'Enter username...',
	LOGOUT: 'Logout',
	USERNAME_INCORRECT: 'Username is incorrect',
	REGISTER_PROMPT: 'Don\'t have an account? Register',
	REGISTER: 'Register',
	SIGN_UP: 'Sign up',
	LOADING: 'Loading...',
	PROVIDER_WARNING: 'useNotes must be used within a NotesProvider',
};